---
- name: Create download path
  file:
    path: "{{ mtail_download_path }}"
    state: directory
    mode: '0755'

- name: set fact binary name
  set_facts:
    mtail_binary_name: "mtail_{{ mtail_version }}_{{ ansible_system | lower }}_amd64"

- name: Put mtail executable
  uri:
    url: "https://github.com/google/mtail/releases/download/{{ mtail_binary_name }}"
    dest: "{{ mtail_download_path }}/{{ mtail_binary_name }}"
    creates: "{{ mtail_download_path }}/{{ mtail_binary_name }}"
    status_code:
    - 200
    - 304
  when: ansible_architecture == "x86_64"
  register: rc

- name: chmod +x
  file:
    path: "{{ mtail_download_path }}/{{ mtail_binary_name }}"
    mode: u+x
  when: rc.changed

- name: Create a symbolic link
  file:
    src: "{{ mtail_download_path }}/{{ mtail_binary_name }}"
    dest: "{{ mtail_binary_path }}/mtail"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link

- name: Put systemd mtail.service unit
  template:
    src: service.j2
    dest: /etc/systemd/system/mtail.service

- name: Put systemd unit
  template:
    src: default.j2
    dest: /etc/default/mtail

- name: Copy mtail programs
  copy:
    src: mtail
    dest: /usr/local/etc/

- name: Enable mtail.service
  systemd:
    name: mtail.service
    daemon_reload: yes
    enabled: yes
    state: started

- name: Copy mtail progs
  copy:
    src: mtail/
    dest: "{{ mtail_progs_path }}"